//! C lowering consumes resolved, typed IR; it never reparses Juyu source.
mod numeric;
use crate::sema::{
    CallTarget, Expression, ExpressionKind as E, Function, Program, Statement as S, Type,
};
use crate::syntax::ast::{BinaryOp as B, UnaryOp as U};
use std::collections::BTreeMap;

/// Emit a complete native executable translation unit. Semantic checking may
/// accept library files, but executable generation requires a valid main.
pub fn generate_c(program: &Program) -> Result<String, String> {
    let main = program
        .functions()
        .iter()
        .find(|f| f.name == "main")
        .ok_or("cannot build executable: missing main function")?;
    let mut emitter = Emitter {
        body: String::new(),
        indent: 0,
        temporary: 0,
        helpers: BTreeMap::new(),
    };
    for function in program.functions() {
        emitter.line(&format!("{};", signature(function)));
    }
    emitter.line("");
    for function in program.functions() {
        emitter.line(&format!("{} {{", signature(function)));
        emitter.indent += 1;
        emitter.statements(&function.body);
        emitter.indent -= 1;
        emitter.line("}");
        emitter.line("");
    }
    emitter.line("int main(void) {");
    emitter.indent += 1;
    if main.result == Type::Void {
        emitter.line(&format!("juyu_fn_{}();", main.id));
        emitter.line("return 0;");
    } else {
        emitter.line(&format!("return (int)juyu_fn_{}();", main.id));
    }
    emitter.indent -= 1;
    emitter.line("}");
    let mut c = String::from("/* Generated by the Juyu bootstrap C backend. */\n#include <stdint.h>\n#include <stdio.h>\n#include <inttypes.h>\n#include <stdbool.h>\n#include <stddef.h>\n#include <stdlib.h>\n#include <string.h>\n#include <math.h>\n#include <float.h>\n\ntypedef struct { const unsigned char *ptr; size_t len; } juyu_str;\n\n");
    for helper in emitter.helpers.values() {
        c.push_str(helper);
        c.push('\n');
    }
    c.push_str(&emitter.body);
    Ok(c)
}

fn signature(f: &Function) -> String {
    let params = if f.params.is_empty() {
        "void".to_owned()
    } else {
        f.params
            .iter()
            .map(|(id, ty)| format!("{} juyu_var_{id}", c_type(*ty)))
            .collect::<Vec<_>>()
            .join(", ")
    };
    format!("{} juyu_fn_{}({params})", c_type(f.result), f.id)
}
fn c_type(ty: Type) -> &'static str {
    match ty {
        Type::Void => "void",
        Type::Bool => "bool",
        Type::Str => "juyu_str",
        Type::I8 => "int8_t",
        Type::I16 => "int16_t",
        Type::I32 => "int32_t",
        Type::I64 => "int64_t",
        Type::U8 => "uint8_t",
        Type::U16 => "uint16_t",
        Type::U32 => "uint32_t",
        Type::U64 => "uint64_t",
        Type::F32 => "float",
        Type::F64 => "double",
    }
}
struct Emitter {
    body: String,
    indent: usize,
    temporary: usize,
    helpers: BTreeMap<String, String>,
}
impl Emitter {
    fn line(&mut self, text: &str) {
        self.body.push_str(&"    ".repeat(self.indent));
        self.body.push_str(text);
        self.body.push('\n');
    }
    fn temp(&mut self, ty: Type, value: &str) -> String {
        let name = format!("juyu_tmp_{}", self.temporary);
        self.temporary += 1;
        self.line(&format!("{} {name} = {value};", c_type(ty)));
        name
    }
    fn statements(&mut self, stmts: &[S]) {
        for stmt in stmts {
            match stmt {
                S::Declare(id, ty, expr) => {
                    let value = self.expression(expr).unwrap();
                    self.line(&format!("{} juyu_var_{id} = {value};", c_type(*ty)));
                }
                S::Assign(id, expr) => {
                    let value = self.expression(expr).unwrap();
                    self.line(&format!("juyu_var_{id} = {value};"));
                }
                S::Evaluate(expr) => {
                    if let Some(value) = self.expression(expr) {
                        self.line(&format!("(void){value};"));
                    }
                }
                S::Return(expr) => {
                    let value = expr.as_ref().and_then(|expr| self.expression(expr));
                    match value {
                        Some(value) => self.line(&format!("return {value};")),
                        None => self.line("return;"),
                    }
                }
                S::Break => self.line("break;"),
                S::Continue => self.line("continue;"),
                S::Block(body) => {
                    self.line("{");
                    self.indent += 1;
                    self.statements(body);
                    self.indent -= 1;
                    self.line("}");
                }
                S::If(cond, yes, no) => {
                    let cond = self.expression(cond).unwrap();
                    self.line(&format!("if ({cond}) {{"));
                    self.indent += 1;
                    self.statements(yes);
                    self.indent -= 1;
                    if !no.is_empty() {
                        self.line("} else {");
                        self.indent += 1;
                        self.statements(no);
                        self.indent -= 1;
                    }
                    self.line("}");
                }
                S::While(cond, body) => {
                    // The condition may contain calls. Recompute it at the loop
                    // head so continue takes the same path as normal iteration.
                    self.line("for (;;) {");
                    self.indent += 1;
                    let cond = self.expression(cond).unwrap();
                    self.line(&format!("if (!{cond}) break;"));
                    self.statements(body);
                    self.indent -= 1;
                    self.line("}");
                }
                S::Loop(body) => {
                    self.line("for (;;) {");
                    self.indent += 1;
                    self.statements(body);
                    self.indent -= 1;
                    self.line("}");
                }
            }
        }
    }
    fn expression(&mut self, expr: &Expression) -> Option<String> {
        let value = match &expr.kind {
            E::Int(n) => format!("(({}){})", c_type(expr.ty), numeric::integer(*n)),
            E::Float(n) => format!("(({}){n:.17e})", c_type(expr.ty)),
            E::Bool(b) => b.to_string(),
            E::String(s) => {
                // Keep ASCII readable; fixed-width octal encodes NUL/UTF-8 and
                // question marks (avoiding C trigraphs) without escape ambiguity.
                let bytes: String = s
                    .bytes()
                    .map(|b| match b {
                        b'"' => "\\\"".into(),
                        b'\\' => "\\\\".into(),
                        32..=126 if b != b'?' => char::from(b).to_string(),
                        _ => format!("\\{b:03o}"),
                    })
                    .collect();
                format!(
                    "((juyu_str){{(const unsigned char *)\"{bytes}\", {}}})",
                    s.len()
                )
            }
            E::Local(id) => format!("juyu_var_{id}"),
            E::Call(target, args) => {
                // Materialization fixes argument evaluation order (left-to-right),
                // which plain C call expressions would leave unspecified.
                let args = args
                    .iter()
                    .map(|arg| self.expression(arg).unwrap())
                    .collect::<Vec<_>>();
                let name = match target {
                    CallTarget::User(id) => format!("juyu_fn_{id}"),
                    CallTarget::Runtime(id) => {
                        let function = &crate::runtime::FUNCTIONS[*id];
                        self.helpers
                            .insert(function.c_name.to_owned(), function.c_source.to_owned());
                        function.c_name.to_owned()
                    }
                };
                format!("{name}({})", args.join(", "))
            }
            E::Cast(inner) => {
                let value = self.expression(inner).unwrap();
                if inner.ty == expr.ty {
                    value
                } else {
                    let (name, helper) = numeric::cast(inner.ty, expr.ty);
                    self.helpers.insert(name.clone(), helper);
                    format!("{name}({value})")
                }
            }
            E::Unary(op, inner) => {
                let value = self.expression(inner).unwrap();
                match op {
                    U::Not => format!("(!{value})"),
                    U::BitNot => format!("(({})~{value})", c_type(expr.ty)),
                    U::Neg if expr.ty.is_integer() => {
                        let (name, helper) = numeric::arithmetic(expr.ty, B::Sub);
                        self.helpers.insert(name.clone(), helper);
                        format!("{name}(0, {value})")
                    }
                    U::Neg => format!("(-{value})"),
                    U::AddressOf => unreachable!("sema excludes pointers"),
                }
            }
            E::Binary(a, op, b) => {
                let left = self.expression(a).unwrap();
                if matches!(op, B::LogicalAnd | B::LogicalOr) {
                    let result = self.temp(Type::Bool, &left);
                    let condition = if *op == B::LogicalAnd {
                        result.clone()
                    } else {
                        format!("!{result}")
                    };
                    self.line(&format!("if ({condition}) {{"));
                    self.indent += 1;
                    let right = self.expression(b).unwrap();
                    self.line(&format!("{result} = {right};"));
                    self.indent -= 1;
                    self.line("}");
                    return Some(result);
                }
                let right = self.expression(b).unwrap();
                if a.ty.is_integer() && matches!(op, B::Add | B::Sub | B::Mul | B::Div | B::Mod) {
                    let (name, helper) = numeric::arithmetic(a.ty, *op);
                    self.helpers.insert(name.clone(), helper);
                    format!("{name}({left}, {right})")
                } else if a.ty == Type::Str {
                    let equal = format!("({left}.len == {right}.len && memcmp({left}.ptr, {right}.ptr, {left}.len) == 0)");
                    if *op == B::Eq {
                        equal
                    } else {
                        format!("(!{equal})")
                    }
                } else {
                    format!("({left} {} {right})", operator(*op))
                }
            }
        };
        if expr.ty == Type::Void {
            self.line(&format!("{value};"));
            None
        } else {
            Some(self.temp(expr.ty, &value))
        }
    }
}
fn operator(op: B) -> &'static str {
    match op {
        B::Add => "+",
        B::Sub => "-",
        B::Mul => "*",
        B::Div => "/",
        B::Mod => "%",
        B::Eq => "==",
        B::NotEq => "!=",
        B::Lt => "<",
        B::LtEq => "<=",
        B::Gt => ">",
        B::GtEq => ">=",
        _ => unreachable!("operator excluded by sema or lowered separately"),
    }
}
