//! Filesystem/process boundary of compilation. The compiler crate itself is pure.
use crate::toolchain;
use juyu_compiler::{check_source, codegen::generate_c, sema::Program};
use std::{
    fs,
    path::{Path, PathBuf},
    process::Command,
    sync::atomic::{AtomicUsize, Ordering},
};

pub fn check(path: &Path) -> Result<Program, String> {
    let source = fs::read_to_string(path).map_err(|e| format!("{}: {e}", path.display()))?;
    check_source(&source).map_err(|e| format!("{}: {e}", path.display()))
}

pub fn build(path: &Path) -> Result<PathBuf, String> {
    // Require a source suffix so an extensionless input can never be overwritten
    // by its output executable. Canonical paths also handle spaces and leading '-'.
    if path.extension().is_none_or(|ext| ext != "ju") {
        return Err("build requires a .ju source file".into());
    }
    let program = check(path)?;
    let c = generate_c(&program)?;
    let path = path.canonicalize().map_err(|e| e.to_string())?;
    if path.extension().is_none_or(|ext| ext != "ju") {
        return Err("canonical source path must also have a .ju extension".into());
    }
    let c_path = path.with_extension("c");
    let binary = path.with_extension("");
    if let Ok(meta) = fs::symlink_metadata(&c_path) {
        if !meta.is_file()
            || !fs::read_to_string(&c_path)
                .is_ok_and(|s| s.starts_with("/* Generated by the Juyu bootstrap C backend. */"))
        {
            return Err(format!(
                "refusing to overwrite non-generated file {}",
                c_path.display()
            ));
        }
    }
    if fs::symlink_metadata(&binary).is_ok_and(|m| m.file_type().is_symlink() || !m.is_file()) {
        return Err(format!(
            "refusing to overwrite non-regular output {}",
            binary.display()
        ));
    }
    fs::write(&c_path, c).map_err(|e| format!("{}: {e}", c_path.display()))?;
    let cc = toolchain::c_compiler()?;
    let scratch = Scratch::new(path.parent().unwrap())?;
    let staged_binary = scratch.0.join("program");
    let status = Command::new(&cc)
        .args([
            "-std=c11",
            "-O2",
            "-Wall",
            "-Werror=implicit-function-declaration",
        ])
        .arg(&c_path)
        .arg("-o")
        .arg(&staged_binary)
        .status()
        .map_err(|e| format!("could not execute C compiler {cc:?}: {e}"))?;
    if !status.success() {
        return Err(format!(
            "C compiler failed ({status}); generated C kept at {}",
            c_path.display()
        ));
    }
    let metadata = fs::symlink_metadata(&staged_binary)
        .map_err(|e| format!("C compiler reported success but produced no executable: {e}"))?;
    if !metadata.is_file() || metadata.len() == 0 {
        return Err("C compiler did not produce a nonempty regular executable".into());
    }
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        if metadata.permissions().mode() & 0o111 == 0 {
            return Err("C compiler output is not executable".into());
        }
    }
    // Publish only after a successful compile and artifact check. Failed builds
    // cannot accidentally run a stale executable from an earlier successful build.
    fs::rename(&staged_binary, &binary)
        .map_err(|e| format!("could not publish executable: {e}"))?;
    Ok(binary)
}

static NEXT: AtomicUsize = AtomicUsize::new(0);
struct Scratch(PathBuf);
impl Scratch {
    fn new(parent: &Path) -> Result<Self, String> {
        loop {
            let path = parent.join(format!(
                ".juyu-build-{}-{}",
                std::process::id(),
                NEXT.fetch_add(1, Ordering::Relaxed)
            ));
            match fs::create_dir(&path) {
                Ok(()) => return Ok(Self(path)),
                Err(e) if e.kind() == std::io::ErrorKind::AlreadyExists => continue,
                Err(e) => return Err(format!("could not create build directory: {e}")),
            }
        }
    }
}
impl Drop for Scratch {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.0);
    }
}
